apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: sock-shop
spec:
  selector:
    name: front-end
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 8079
  type: NodePort
