apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-admin-sockshop
  namespace: sock-shop
subjects:
- kind: ServiceAccount
  name: litmus-admin
  namespace: litmus
roleRef:
  kind: ClusterRole
  name: litmus-admin
  apiGroup: rbac.authorization.k8s.io